# Generated by Django 5.0.6 on 2024-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=10),
        ),
    ]
