# Generated by Django 5.0.6 on 2024-06-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_task_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_app.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
